# Generated by Django 3.0.8 on 2020-07-31 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='album title', max_length=100)),
                ('artist', models.CharField(help_text='album artist', max_length=100)),
                ('genre', models.CharField(help_text='album genre', max_length=50)),
                ('year', models.DateField(help_text='album year')),
                ('image', models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='song title', max_length=100)),
                ('artist', models.CharField(help_text='song artist', max_length=100)),
                ('genre', models.CharField(help_text='song genre', max_length=20)),
                ('sfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac'])])),
                ('image', models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
